using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("net-4.5.win32; debug")]
[assembly: AssemblyProductAttribute("Spring.NET Framework 0.0.0 for .NET 4.5")]
[assembly: AssemblyCompanyAttribute("SpringSource")]
[assembly: AssemblyCopyrightAttribute("Copyright 2002-2018 Spring.NET Framework Team.")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.0.0.45000")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.45000")]

